### ISSUE TITLE
Validator errors for NarrativeLink extension with use of urn:uuid

### ISSUE THREAD

**Issue by jddamore** [hapifhir/org.hl7.fhir.core#1071]
As part of the IPS connectathon and other work, we have been working to create a strategy for creating narrative links for individual resources when referenced in the Composition.section.text

The validator currently throws 2 errors on the attached sample which we believe should be fixed in the validator: 

1) UUIDs must be valid (and lowercase). The uuid in the attached is all lowercase before the fragment. Fragments that use # are allowable per the  specification http://www.watersprings.org/pub/id/draft-ietf-urnbis-rfc2141bis-urn-07.html#rfc.section.4.3 

2) URL value 'http://hl7.org/fhir/StructureDefinition/NarrativeLink' does not resolve. The url does resolve using the uuid in the Composition.section.text. 

Please feel free to reach out if you have additional question. @jamesagnew was involved in the review so he also knows about the issue. 

[example_narrative_link_validator_issue_urn.json.txt](https://github.com/hapifhir/org.hl7.fhir.core/files/10421161/example_narrative_link_validator_issue_urn.json.txt)

**Comment by grahamegrieve** [comment]
1. Agree. fixed
2. the case is wrong: 'http://hl7.org/fhir/StructureDefinition/*n*arrativeLink'

**Comment by jddamore** [comment]
Agree on link. PR opened to fix with @jamesagnew https://github.com/hapifhir/hapi-fhir/pull/4444

**Comment by cooksheridan** [comment]
@jamesagnew So the case was fixed in https://github.com/hapifhir/hapi-fhir/pull/4444 but... I am seeing a new round of errors now that the case has been fixed where the validator is expressing that the extension is expecting a valueUrl not the valueUri that is currently present in the Jan 2023 Connectathon samples and the $summary documents currently generated in the hapi.fhir server. "Bundle.entry[3].resource.ofType(MedicationStatement).extension[0]: The Extension 'http://hl7.org/fhir/StructureDefinition/narrativeLink' definition allows for the types [url] but found type uri on line 277"
