### ISSUE TITLE
Wrong type for url parameter when calling $validate-code

### ISSUE THREAD

**Issue by lawley** [hapifhir/org.hl7.fhir.core#1175]
`BaseWorkContext.validateOnServer` incorrectly uses `StringType` rather than `UriType` when calling `$validate-code` -- see line 1216 cf line 1214.

https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/context/BaseWorkerContext.java#L1216

This results in failures when external terminology servers like Ontoserver are called as the HAPI framework (correctly) rejects such (POST) requests.

**Comment by grahamegrieve** [comment]
I think this is fixed now - can it be closed?

**Comment by dotasek** [comment]
This is the code as it was when the issue was created:

https://github.com/hapifhir/org.hl7.fhir.core/blob/8dd61f4b2ea4f428bc4566a7805e2fd85ec97001/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/context/BaseWorkerContext.java#L1215C3-L1217C8

And this is as it stands now:

https://github.com/hapifhir/org.hl7.fhir.core/blob/eef3ebc5f1e170f67f89289fcc6cb4ca0ff9e94c/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/context/BaseWorkerContext.java#L1308C9-L1310C8

It looks fixed to me, and just in case, I'm adding a unit test: https://github.com/hapifhir/org.hl7.fhir.core/pull/1345. I'll close once that's merged.
