### ISSUE TITLE
CLI: placeholders like {{FHIR_CURRENT_VERSION}} not replaced in `-help` output

### ISSUE THREAD

**Issue by DarthGizka** [hapifhir/org.hl7.fhir.core#1319]
Invoking the validator CLI with `-help` (or without indication as to what to do) results in a text in which some placeholders have not been replaced:

```
FHIR Validation tool Version 6.0.16 (Git# 8bd0f0b1ad54). Built 2023-06-21T07:41:16.718Z (6 hours old)
  Java:   17.0.7 from C:\Program Files\Java\jdk-17 on amd64 (64bit). 8120MB available

WARNING: Default file encoding is windows-1252 which may cause unexpected results.
         To fix this issue, run this program with the parameter '-Dfile.encoding=UTF-8'
         Future releases may not be able to run at all with encoding windows-1252


This is the help text for default usage of the validator. Help for other modes
...
-version [ver]: The FHIR version to use.
       This can only appear once.
       valid values {{FHIR_MAJOR_VERSIONS}} or {{FHIR_MINOR_VERSIONS}}
       Default value is {{FHIR_CURRENT_VERSION}}
...
```

This is problably not quite as intended.

Note: the file encoding warning is probably spurious. The JVM *was* started with `-Dfile.encoding=UTF-8`, and in other operating modes this is sufficient to make the warning disappear.

**Comment by dotasek** [comment]
Fixed in the above merge.

As for character encoding warnings, I do not get these, with `-Dfile.encoding=UTF-8` or `-Dfile.encoding=UTF8` set. The default setting, as predicted, produces the warning. This is with Eclipse Adoptium 17.0.4.8-hotspot on Windows.

If you can replicate @DarthGizka, this IS a concern warranting another issue. Similar logic is in IG publisher and it will fail painfully far in the publishing process if character encoding isn't correct.
