### ISSUE TITLE
Validator does not show correct error message from Bundle.element

### ISSUE THREAD

**Issue by yunwwang** [hapifhir/org.hl7.fhir.core#464]
I tried to use FHIR validator_cli.jar to validate two bundles for (VCI IG) with invalid resource.  In the first one I removed Patient.name. The error message is strange: 
```quote
  Error @ Bundle (line 1, col2) : Bundle.entry:vaccineCredentialPatient: minimum required = 1, but only found 0 (from http://hl7.org/fhir/us/smarthealthcards-vaccination/StructureDefinition/vaccine-credential-bundle)
  Information @ Bundle.entry[0] (line 6, col6) : This element does not match any known slice defined in the profile http://hl7.org/fhir/us/smarthealthcards-vaccination/StructureDefinition/vaccine-credential-bundle
```
In the second one, I removed Immunizaiton.occurrenceDateTime. This time, validator returned correct error:
```quote
  Error @ Bundle.entry[1].resource.ofType(Immunization) (line 63, col21) : Immunization.occurrence[x]: minimum required = 1, but only found 0 (from http://hl7.org/fhir/StructureDefinition/Immunization)
  Information @ Bundle.entry[1] (line 45, col6) : This element does not match any known slice defined in the profile http://hl7.org/fhir/us/smarthealthcards-vaccination/StructureDefinition/vaccine-credential-bundle
```
Attached VCI IG package which contains both StructureDefintions and examples.
[package (1).zip](https://github.com/hapifhir/org.hl7.fhir.core/files/6173829/package.1.zip)

**Comment by yunwwang** [comment]
Additional finding: In the previous test, the Bundle has two Immunizations. I tested again with only one Immunization entry which did not have required occurenceDatetime. This time I got similar but different error
```quote
  Error @ Bundle (line 1, col2) : Bundle.entry:vaccineCredentialImmunization: minimum required = 1, but only found 0 (from http://hl7.org/fhir/us/smarthealthcards-vaccination/StructureDefinition/vaccine-credential-bundle)
  Error @ Bundle.entry[1].resource.ofType(Immunization) (line 63, col21) : Immunization.occurrence[x]: minimum required = 1, but only found 0 (from http://hl7.org/fhir/StructureDefinition/Immunization)
  Information @ Bundle.entry[1] (line 45, col6) : This element does not match any known slice defined in the profile http://hl7.org/fhir/us/smarthealthcards-vaccination/StructureDefinition/vaccine-credential-bundle
```
My question is why the patient one did not show the detailed failure like Patient.name minimum required = 1, but found 0.

**Comment by nkarip** [comment]
The validator is not able to recognize a Patient without name as an instance of VaccineCredentialPatient, as it does not meet the requirements for that profile. Hence the validator is telling you that there is no VaccineCredentialPatient in the bundle. This is expected behavior. In general, you will need to validate each bundle entry resource separately using the correct profile before validating the bundle.

The second error is a similar instance. When you have 2 Immunizations, one that meets the criteria for the VaccineCredentialImmunization, the validator recognized the requirement for at least 1 VaccineCredentialImmunization in the bundle as filled. Without the occurenceDateTime, the Immunization entry is not a valid VaccineCredentialImmunization and the http://hl7.org/fhir/StructureDefinition/Immunization profile is instead used for validation.

**Comment by yunwwang** [comment]
What I am wondering is the difference that the Immunization error is reported correctly as " Error @ Bundle.entry[1].resource.ofType(Immunization) (line 63, col21) : Immunization.occurrence[x]: minimum required = 1, but only found 0 (from http://hl7.org/fhir/StructureDefinition/Immunization)" while patient error is not.

**Comment by nkarip** [comment]
Name is not required in the core Patient profile, so there is no error indicating that it is missing. The occurrence[x] is required in the core Immunization profile, so it is showing that resource validation error. 

The validator has no way of knowing you want to validate a resource in the bundle against VaccineCredentialPatient and not core Patient. You need to validate the patient resource separately and explicitly tell it to use the VaccineCredentialPatient profile, then validate the bundle.

**Comment by yunwwang** [comment]
Thanks @nkarip. I am still confused. If validator_cli does not validate against VaccineCredentialPatient profile, how does it know the patient is not valid and reported that "Information @ Bundle.entry[0] (line 6, col6) : This element does not match any known slice defined in the profile http://hl7.org/fhir/us/smarthealthcards-vaccination/StructureDefinition/vaccine-credential-bundle".

**Comment by nkarip** [comment]
I think they are separate requirement checks. The bundle requires "bundle must have exactly one VaccineCredentialPatient", which is one check. We can extrapolate that any Patient instance in the bundle also needs to validate against VaccineCredentialPatient, but I don't think the instance validator can make that leap as the resource does not explicitly state a profile in meta. This could be suggested as an enhancement to the validator, but I don't think there is anything in the IG that could be changed.

**Comment by grahamegrieve** [comment]
the patient is not valid against the profile, but that cannot be reported as an issue against the resource itself unless either the resource claims it conforms, of the validator is asked directly to validate the resource directly. Otherwise the outcome will be littered with errors that say why one resource doesn't conform to a profile, though it doesn't need to. There is a parameter to ask to see the inner workings of slicing reasoning, which appears to be what you're asking for here.
