### ISSUE TITLE
unable to parse character reference 'frac12'

### ISSUE THREAD

**Issue by kdusara** [hapifhir/org.hl7.fhir.core#660]
XhtmlParser.class throws exception 'unable to parse character reference 'frac12''
for the string '1/2 Strength'
when its html encoded correctly as "&frac12; STRENGTH"

**Comment by bwright36** [comment]
Digging into this a little bit in XhtmlParser.java in package package org.hl7.fhir.utilities.xhtml, it seems that the root cause is that while the entities are added into the entities lookup hashmap with the leading ampersand and trailing semicolon (example: "\&apos;")

>   private void defineEntities() {
>     entities.put("\&AElig;", "\u00C6");
>     entities.put("\&AMP;", "\u0026");

When the lookup occurs, it does not include the ampersand and semicolon (example: "apos").

>   private void parseLiteral(StringBuilder s) throws IOException, FHIRFormatError {
>     // UInt16 w;
>     **readChar();
>     String c = readUntil(";&'\"><");**
>     if (c.isEmpty())
>       throw new FHIRFormatError("Invalid literal declaration following text: " + s);
>     else if (c.charAt(0) == '#') {
>       if (isInteger(c.substring(1), 10))
>         s.append((char) Integer.parseInt(c.substring(1)));
>       else if (c.charAt(1) == 'x' && isInteger(c.substring(2), 16))
>         s.append((char) Integer.parseInt(c.substring(2), 16));
>     **} else if (entities.containsKey(c)) {
>       s.append(entities.get(c));**
>     } else if (c.equals("apos"))
>       s.append('\'');
>    } else ...

So the literal is not found unless it is explicitly added to the else statements following the entities hashmap check.

I also did the cross check in the comment below, and all the codes that are included in the ELSE statements are also included in the entities hashmap.

      // what's going on here? 
      // the contents that follow already existed, and then I added the routine to populate the entities 
      // which was generated from other code. The code that follows is probably redundant, but I haven't
      // cross checked it. some is welcome to do so... (GG 8-Nov 2021)

A possible fix is to add back in the delimiters when searching:

>   private String delimitedLiteral(String c) {
>     return "&" + c + ";";
>   }
> 
>   private void parseLiteral(StringBuilder s) throws IOException, FHIRFormatError {
>     // UInt16 w;
>     readChar();
>     String c = readUntil(";&'\"><");
>     // c contains the literal text without delimiters i.e. "apos" instead of "&apos;" 
>     // for searching in entities (which all have format &xxx;) we need to add the delimiting characters back
>     String entitySearchKey = delimitedLiteral(c);
>     if (c.isEmpty())
>       throw new FHIRFormatError("Invalid literal declaration following text: " + s);
>     else if (c.charAt(0) == '#') {
>       if (isInteger(c.substring(1), 10))
>         s.append((char) Integer.parseInt(c.substring(1)));
>       else if (c.charAt(1) == 'x' && isInteger(c.substring(2), 16))
>         s.append((char) Integer.parseInt(c.substring(2), 16));
>     } else if (entities.containsKey(entitySearchKey)) {
>       s.append(entities.get(entitySearchKey));
>     } else if (!mustBeWellFormed) {
>       // we guess that this is an accidentally unescaped &
>       s.append("&"+c);
>     } else {
>       throw new FHIRFormatError("unable to parse character reference '" + c + "'' (last text = '" + lastText + "'" + descLoc());
>     }
>   }

Then the delimited version also has to be added in the parseDocTypeEntities:

      entities.put(delimitedLiteral(n), v);
